using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Rig.Analysis;
using Rig.Analysis.Rules;
using Rig.Domain.Data;
using Rig.Domain.Functions;
using Rig.Tests.Fixtures;
using Shouldly;

namespace Rig.Tests.Analysis;

public sealed class LiveScaleGeneratorTests
{
    [Test]
    public async Task Smoke_corpus_is_byte_deterministic_executable_and_semantically_non_vacuous()
    {
        using var first = await LiveScalePlayground.GenerateAsync();
        using var second = await LiveScalePlayground.GenerateAsync();

        var firstFiles = first.FileInventory();
        var secondFiles = second.FileInventory();
        firstFiles.Keys.ShouldBe(secondFiles.Keys, ignoreOrder: false);
        foreach (var path in firstFiles.Keys)
        {
            firstFiles[path].ShouldBe(secondFiles[path], $"generated bytes differ for {path}");
        }
        first.CorpusHash.ShouldBe(second.CorpusHash);
        first.EditTraceHash.ShouldBe(second.EditTraceHash);
        first.RecomputeCorpusHash().ShouldBe(first.CorpusHash);

        using var manifest = JsonDocument.Parse(firstFiles["corpus-manifest.json"]);
        var dimensions = manifest.RootElement.GetProperty("dimensions");
        dimensions.GetProperty("projectCount").GetInt32().ShouldBe(12);
        dimensions.GetProperty("totalCSharpFiles").GetInt32().ShouldBe(240);
        dimensions.GetProperty("estimatedReferenceCount").GetInt64().ShouldBe(16_800);
        manifest.RootElement.GetProperty("projects").GetArrayLength().ShouldBe(12);
        firstFiles.Keys.Count(path => path.EndsWith(".cs", StringComparison.Ordinal)).ShouldBe(240);

        AssertPortableContent(first, firstFiles);
        AssertTrace(first, firstFiles, manifest.RootElement);
        AssertTopology(manifest.RootElement);
        AssertPresetCalibration();

        await first.RestoreAsync();
        await second.RestoreAsync();
        var rules = RuleSetLoader.Load(first.WorkingDirectory);
        var facts = await SolutionAnalyzer.AnalyzeAsync(first.SolutionPath, rules);
        var secondRules = RuleSetLoader.Load(second.WorkingDirectory);
        var secondFacts = await SolutionAnalyzer.AnalyzeAsync(second.SolutionPath, secondRules);
        facts.CompilationHealth.ShouldNotBeNull().IsClean.ShouldBeTrue();
        secondFacts.CompilationHealth.ShouldNotBeNull().IsClean.ShouldBeTrue();

        var canonicalFacts = CanonicalFacts(facts, first.WorkingDirectory);
        var secondCanonicalFacts = CanonicalFacts(secondFacts, second.WorkingDirectory);
        FactHash(canonicalFacts).ShouldBe(FactHash(secondCanonicalFacts));
        canonicalFacts.ShouldBe(secondCanonicalFacts, ignoreOrder: false);

        (facts.Symbols ?? []).Count.ShouldBeGreaterThan(0);
        (facts.References ?? []).Count.ShouldBeGreaterThan(0);
        (facts.TypeRelations ?? []).Count.ShouldBeGreaterThan(0);
        (facts.DispatchFacts ?? []).Count.ShouldBeGreaterThan(0);
        (facts.SourceFiles ?? [])
            .Count(file =>
                Path.GetFileName(file.FilePath).StartsWith("File", StringComparison.Ordinal)
                && file.FilePath.EndsWith(".cs", StringComparison.Ordinal)
            )
            .ShouldBe(240);

        (facts.Symbols ?? []).ShouldContain(symbol => symbol.Modifiers.Split(' ').Contains("async"));
        (facts.TypeRelations ?? []).ShouldContain(relation => relation.RelationKind == "interface");
        (facts.TypeRelations ?? []).ShouldContain(relation => relation.RelationKind == "base");
        (facts.DispatchFacts ?? []).ShouldContain(dispatch => dispatch.Kind == "impl");
        (facts.DispatchFacts ?? []).ShouldContain(dispatch => dispatch.Kind == "override");
        (facts.References ?? []).ShouldContain(reference => reference.RefKind == "methodGroup");
        (facts.References ?? []).ShouldContain(reference =>
            reference.TargetSymbolId.Contains("System.IO.File.Exists", StringComparison.Ordinal)
        );
        (facts.References ?? []).ShouldContain(reference =>
            reference.RefKind == "invocation"
            && reference.TargetInSource
            && reference.TargetAssembly == "Core.Contracts"
            && Normalize(reference.FilePath, first.WorkingDirectory).StartsWith("Feature", StringComparison.Ordinal)
        );

        var effects = FactEffectDeriver.Derive(FactProjection.Invocations(facts), rules.Effects);
        effects.ShouldContain(effect => effect.Provider == "io" && effect.Operation == "read");

        await AssertResetSafetyAsync(second);
        await AssertGeneratedCodeArmAsync(first);

        Console.WriteLine(first.GeneratorOutput);
        Console.WriteLine(
            $"semantic counts: {(facts.Symbols ?? []).Count} symbols / {(facts.References ?? []).Count} references / "
                + $"{(facts.TypeRelations ?? []).Count} type relations / {(facts.DispatchFacts ?? []).Count} dispatch / {effects.Count} effects"
        );
    }

    private static void AssertPortableContent(LiveScalePlayground corpus, IReadOnlyDictionary<string, byte[]> files)
    {
        var canonicalOutput = corpus.WorkingDirectory.Replace('\\', '/');
        foreach (var (path, bytes) in files)
        {
            path.ShouldNotContain("\\");
            bytes.AsSpan().StartsWith(Encoding.UTF8.Preamble).ShouldBeFalse($"BOM in {path}");
            bytes.ShouldNotContain((byte)'\r', $"CR newline in {path}");
            Encoding
                .UTF8.GetString(bytes)
                .Replace('\\', '/')
                .Contains(canonicalOutput, StringComparison.Ordinal)
                .ShouldBeFalse($"absolute output path embedded in {path}");
        }

        var solutionProjects = Encoding
            .UTF8.GetString(files["LiveScale.slnx"])
            .Split('\n', StringSplitOptions.RemoveEmptyEntries)
            .Where(line => line.Contains("<Project Path=", StringComparison.Ordinal))
            .ToArray();
        solutionProjects.ShouldBe(solutionProjects.Order(StringComparer.Ordinal).ToArray(), ignoreOrder: false);

        var sources = files
            .Where(pair => pair.Key.EndsWith(".cs", StringComparison.Ordinal))
            .Select(pair => Encoding.UTF8.GetString(pair.Value))
            .ToArray();
        sources.Count(text => text.Contains("vocabulary-", StringComparison.Ordinal)).ShouldBe(240);
        sources
            .SelectMany(text => Lines(text).Where(line => line.Contains("private const string UniqueText", StringComparison.Ordinal)))
            .Distinct()
            .Count()
            .ShouldBe(240);
        files.Keys.ShouldNotContain(path => path.EndsWith(".g.cs", StringComparison.Ordinal));
    }

    private static void AssertTrace(LiveScalePlayground corpus, IReadOnlyDictionary<string, byte[]> files, JsonElement manifest)
    {
        using var trace = JsonDocument.Parse(files["edit-trace.json"]);
        trace.RootElement.GetProperty("replayPolicy").GetString().ShouldBe("apply-then-revert-each-step");
        var edits = trace.RootElement.GetProperty("edits").EnumerateArray().ToArray();
        edits.Length.ShouldBe(20);
        edits.Count(edit => edit.GetProperty("kind").GetString() == "body").ShouldBe(12);
        edits.Count(edit => edit.GetProperty("kind").GetString() == "batch").ShouldBe(4);
        edits.ShouldContain(edit => edit.GetProperty("scenario").GetString() == "save-all");
        edits.ShouldContain(edit => edit.GetProperty("scenario").GetString() == "branch-switch");
        edits.Select(edit => edit.GetProperty("targetClass").GetString()).ShouldContain("hot");
        edits.Select(edit => edit.GetProperty("targetClass").GetString()).ShouldContain("hub");
        edits.Select(edit => edit.GetProperty("targetClass").GetString()).ShouldContain("medium");
        edits.Select(edit => edit.GetProperty("targetClass").GetString()).ShouldContain("leaf");
        edits
            .Where(edit => edit.GetProperty("targetClass").GetString() == "hot")
            .SelectMany(edit => edit.GetProperty("mutations").EnumerateArray())
            .Select(mutation => mutation.GetProperty("file").GetString())
            .Count(file => file == "Pages/File0000.cs")
            .ShouldBeGreaterThanOrEqualTo(4);

        var replay = files
            .Where(pair => pair.Key.EndsWith(".cs", StringComparison.Ordinal))
            .ToDictionary(pair => pair.Key, pair => Encoding.UTF8.GetString(pair.Value), StringComparer.Ordinal);
        foreach (var edit in edits)
        {
            var before = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var mutation in edit.GetProperty("mutations").EnumerateArray())
            {
                var path = mutation.GetProperty("file").GetString()!;
                var original = replay[path];
                var marker = mutation.GetProperty("marker").GetString()!;
                var replacement = mutation.GetProperty("replacement").GetString()!;
                original.Contains(marker, StringComparison.Ordinal).ShouldBeTrue($"trace marker absent from {path}");
                CountOccurrences(original, marker).ShouldBe(1);
                before[path] = original;
                replay[path] = original.Replace(marker, replacement, StringComparison.Ordinal);

                var operation = mutation.GetProperty("operation").GetString();
                if (operation == "change-local-expression")
                {
                    marker.ShouldContain("var total = value +");
                    marker.ShouldContain("// body-edit-marker");
                    marker.ShouldNotContain("const");
                    replacement.ShouldNotContain("const");
                }
                else if (operation == "add-member")
                {
                    replacement.ShouldContain("public static int AddedSurface");
                }
            }

            foreach (var mutation in edit.GetProperty("mutations").EnumerateArray().Reverse())
            {
                var path = mutation.GetProperty("file").GetString()!;
                var reverseMarker = mutation.GetProperty("reverseMarker").GetString()!;
                var reverseReplacement = mutation.GetProperty("reverseReplacement").GetString()!;
                replay[path].Contains(reverseMarker, StringComparison.Ordinal).ShouldBeTrue();
                CountOccurrences(replay[path], reverseMarker).ShouldBe(1);
                replay[path] = replay[path].Replace(reverseMarker, reverseReplacement, StringComparison.Ordinal);
                replay[path].ShouldBe(before[path]);
            }
        }

        var queries = trace.RootElement.GetProperty("querySeeds").EnumerateArray().ToArray();
        queries.ShouldContain(query => query.GetProperty("relation").GetString() == "intersects");
        queries.ShouldContain(query => query.GetProperty("relation").GetString() == "disjoint");
        var editsById = edits.ToDictionary(edit => edit.GetProperty("id").GetString()!, StringComparer.Ordinal);
        var projectDependencies = ProjectDependencies(manifest);
        foreach (var query in queries)
        {
            var editId = query.GetProperty("editId").GetString()!;
            editsById.ShouldContainKey(editId);
            var dirtyFile = query.GetProperty("dirtyFile").GetString()!;
            editsById[editId]
                .GetProperty("mutations")
                .EnumerateArray()
                .ShouldContain(mutation => mutation.GetProperty("file").GetString() == dirtyFile);
            var queryFile = query.GetProperty("queryFile").GetString()!;
            files.ShouldContainKey(dirtyFile);
            files.ShouldContainKey(queryFile);

            if (query.GetProperty("relation").GetString() == "intersects")
            {
                dirtyFile.ShouldBe(queryFile);
            }
            else
            {
                dirtyFile.ShouldNotBe(queryFile);
                var dirtyProject = dirtyFile.Split('/')[0];
                var queryProject = queryFile.Split('/')[0];
                TransitiveDependencies(queryProject, projectDependencies).ShouldNotContain(dirtyProject);
            }
        }
        corpus.EditTraceHash.ShouldBe(Convert.ToHexStringLower(System.Security.Cryptography.SHA256.HashData(files["edit-trace.json"])));
    }

    private static void AssertTopology(JsonElement manifest)
    {
        var projects = manifest
            .GetProperty("projects")
            .EnumerateArray()
            .Select(project => new
            {
                Name = project.GetProperty("name").GetString()!,
                Role = project.GetProperty("role").GetString()!,
                Files = project.GetProperty("cSharpFileCount").GetInt32(),
                References = project.GetProperty("projectReferences").EnumerateArray().Select(value => value.GetString()!).ToArray(),
            })
            .ToArray();
        var dependencies = projects.ToDictionary(project => project.Name, project => project.References, StringComparer.Ordinal);
        var transitiveDependents = projects.ToDictionary(
            project => project.Name,
            _ => new HashSet<string>(StringComparer.Ordinal),
            StringComparer.Ordinal
        );
        foreach (var candidate in projects)
        {
            foreach (var dependency in TransitiveDependencies(candidate.Name, dependencies))
            {
                transitiveDependents[dependency].Add(candidate.Name);
            }
        }

        projects.Count(project => project.References.Contains("Core.Contracts", StringComparer.Ordinal)).ShouldBe(11);
        projects.Count(project => project.Role.StartsWith("oversized-", StringComparison.Ordinal)).ShouldBe(2);
        projects
            .Where(project => project.Role.StartsWith("oversized-", StringComparison.Ordinal))
            .ShouldAllBe(project => project.Files > 18);
        projects.ShouldContain(project =>
            project.Role == "feature"
            && project.References.Count(reference =>
                dependencies[reference].Any(grandparent => grandparent.StartsWith("Feature", StringComparison.Ordinal))
            ) >= 2
        );
        projects.ShouldContain(project => project.Role == "feature" && project.References.Any(reference => dependencies[reference].Any()));

        var referenced = projects.SelectMany(project => project.References).ToHashSet(StringComparer.Ordinal);
        projects.ShouldContain(project => !referenced.Contains(project.Name), "leaf project missing");
        projects.Single(project => project.Name == "Pages").Files.ShouldBeGreaterThan(18);
        projects.Single(project => project.Name == "DataAccessTier").Files.ShouldBeGreaterThan(18);

        var halfProjectThreshold = projects.Length / 2;
        var broadHubs = projects.Where(project => transitiveDependents[project.Name].Count >= halfProjectThreshold).ToArray();
        broadHubs.Length.ShouldBe(2);
        broadHubs.Select(project => project.Role).ShouldBe(new[] { "core-contracts-hub", "runtime" }, ignoreOrder: true);

        var transitiveCounts = projects.Select(project => transitiveDependents[project.Name].Count).Order().ToArray();
        transitiveCounts[transitiveCounts.Length / 2].ShouldBeLessThanOrEqualTo(3);
        projects
            .Where(project => project.Role != "core-contracts-hub" && project.Role != "runtime")
            .ShouldAllBe(project => transitiveDependents[project.Name].Count < halfProjectThreshold);

        var oversizedNames = projects
            .Where(project => project.Role.StartsWith("oversized-", StringComparison.Ordinal))
            .Select(project => project.Name)
            .ToHashSet();
        var features = projects.Where(project => project.Role == "feature").ToArray();
        var featuresPullingOversized = features.Count(project => transitiveDependents[project.Name].Overlaps(oversizedNames));
        featuresPullingOversized.ShouldBeGreaterThanOrEqualTo((features.Length * 3) / 5);
        var fileCounts = projects.ToDictionary(project => project.Name, project => project.Files, StringComparer.Ordinal);
        var featureCascadeFiles = features
            .Select(project => project.Files + transitiveDependents[project.Name].Sum(dependent => fileCounts[dependent]))
            .Order()
            .ToArray();
        featureCascadeFiles[featureCascadeFiles.Length / 2].ShouldBeGreaterThanOrEqualTo(48);

        var emitted = manifest.GetProperty("dimensions").GetProperty("topologySummary");
        emitted.GetProperty("maximumTransitiveDependents").GetInt32().ShouldBe(transitiveCounts[^1]);
        emitted.GetProperty("medianTransitiveDependents").GetInt32().ShouldBe(transitiveCounts[transitiveCounts.Length / 2]);
        emitted.GetProperty("projectsWithAtLeastHalfOfProjectsDependingOnThem").GetInt32().ShouldBe(2);
        emitted.GetProperty("featuresPullingOversizedProjects").GetInt32().ShouldBe(featuresPullingOversized);
    }

    private static void AssertPresetCalibration()
    {
        var repositoryRoot = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
        using var seed = JsonDocument.Parse(
            File.ReadAllText(Path.Combine(repositoryRoot, "playgrounds", "LiveScaleSeed", "manifest.json"))
        );
        var presets = seed.RootElement.GetProperty("presets");

        long Estimate(string name)
        {
            var preset = presets.GetProperty(name);
            var projectCount = preset.GetProperty("projectCount").GetInt32();
            var oversizedCount = preset.GetProperty("topology").GetProperty("oversizedProjectIndices").GetArrayLength();
            var files =
                projectCount * preset.GetProperty("filesPerProject").GetInt32()
                + oversizedCount * preset.GetProperty("oversizedProjectExtraFiles").GetInt32();
            return (long)files * preset.GetProperty("methodsPerFile").GetInt32() * (preset.GetProperty("callsPerMethod").GetInt32() + 5L);
        }

        Estimate("smoke").ShouldBe(16_800);
        Estimate("scale").ShouldBeInRange(800_000, 1_500_000);
        Estimate("stress").ShouldBeInRange(2_200_000, 2_600_000);
    }

    private static async Task AssertResetSafetyAsync(LiveScalePlayground corpus)
    {
        var marker = Path.Combine(corpus.WorkingDirectory, ".live-scale-corpus");
        var sentinelDirectory = Path.Combine(corpus.WorkingDirectory, "do-not-delete");
        Directory.CreateDirectory(sentinelDirectory);
        var sentinel = Path.Combine(sentinelDirectory, "sentinel.txt");
        await File.WriteAllTextAsync(sentinel, "retain me");
        await File.WriteAllTextAsync(marker, "LiveScaleGenerator schema 1\nextra\n");

        var invalidMarker = await LiveScalePlayground.RunGeneratorAsync("smoke", corpus.WorkingDirectory, 20260822);
        invalidMarker.ExitCode.ShouldNotBe(0);
        invalidMarker.StandardError.ShouldContain("Refusing to replace non-generator directory");
        File.Exists(sentinel).ShouldBeTrue();

        if (!OperatingSystem.IsWindows())
        {
            var symlinkOutput = Path.Combine(corpus.RootDirectory, "symlink-marker-output");
            Directory.CreateDirectory(symlinkOutput);
            var target = Path.Combine(corpus.RootDirectory, "valid-marker-target");
            await File.WriteAllTextAsync(target, "LiveScaleGenerator schema 1\n", new UTF8Encoding(false));
            File.CreateSymbolicLink(Path.Combine(symlinkOutput, ".live-scale-corpus"), target);
            var symlinkSentinel = Path.Combine(symlinkOutput, "sentinel.txt");
            await File.WriteAllTextAsync(symlinkSentinel, "retain me");

            var symlinkMarker = await LiveScalePlayground.RunGeneratorAsync("smoke", symlinkOutput, 20260822);
            symlinkMarker.ExitCode.ShouldNotBe(0);
            symlinkMarker.StandardError.ShouldContain("Refusing to replace non-generator directory");
            File.Exists(symlinkSentinel).ShouldBeTrue();
        }
    }

    private static async Task AssertGeneratedCodeArmAsync(LiveScalePlayground corpus)
    {
        var output = Path.Combine(corpus.RootDirectory, "generated-arm");
        var result = await LiveScalePlayground.RunGeneratorAsync("smoke", output, 20260822, includeGenerated: true);
        result.ExitCode.ShouldBe(0, result.StandardError);
        Directory.EnumerateFiles(output, "*.g.cs", SearchOption.AllDirectories).Count().ShouldBe(12);
        Directory.EnumerateFiles(output, "*.cs", SearchOption.AllDirectories).Count().ShouldBe(252);
        using var manifest = JsonDocument.Parse(await File.ReadAllTextAsync(Path.Combine(output, "corpus-manifest.json")));
        manifest.RootElement.GetProperty("includesGeneratedCode").GetBoolean().ShouldBeTrue();
    }

    private static Dictionary<string, string[]> ProjectDependencies(JsonElement manifest) =>
        manifest
            .GetProperty("projects")
            .EnumerateArray()
            .ToDictionary(
                project => project.GetProperty("name").GetString()!,
                project => project.GetProperty("projectReferences").EnumerateArray().Select(reference => reference.GetString()!).ToArray(),
                StringComparer.Ordinal
            );

    private static HashSet<string> TransitiveDependencies(string project, IReadOnlyDictionary<string, string[]> dependencies)
    {
        var result = new HashSet<string>(StringComparer.Ordinal);
        var pending = new Stack<string>(dependencies[project]);
        while (pending.TryPop(out var dependency))
        {
            if (!result.Add(dependency))
            {
                continue;
            }
            foreach (var ancestor in dependencies[dependency])
            {
                pending.Push(ancestor);
            }
        }
        return result;
    }

    private static string[] CanonicalFacts(AnalysisResult facts, string root)
    {
        var rows = new List<string>();
        rows.Add(
            "analysis|"
                + JsonSerializer.Serialize(
                    new
                    {
                        SolutionPath = Normalize(facts.SolutionPath, root),
                        facts.ProjectIdentity,
                        SourceProjectPath = facts.SourceProjectPath is null ? null : Normalize(facts.SourceProjectPath, root),
                    }
                )
        );
        rows.AddRange(
            facts.SourceFiles.Select(fact => "source|" + JsonSerializer.Serialize(fact with { FilePath = Normalize(fact.FilePath, root) }))
        );
        rows.AddRange(
            facts.DiRegistrations.Select(fact => "di|" + JsonSerializer.Serialize(fact with { FilePath = Normalize(fact.FilePath, root) }))
        );
        rows.AddRange(
            (facts.Symbols ?? []).Select(fact =>
                "symbol|" + JsonSerializer.Serialize(fact with { FilePath = Normalize(fact.FilePath, root) })
            )
        );
        rows.AddRange(
            (facts.References ?? []).Select(fact =>
                "reference|" + JsonSerializer.Serialize(fact with { FilePath = Normalize(fact.FilePath, root) })
            )
        );
        rows.AddRange(
            (facts.TypeRelations ?? []).Select(fact =>
                "relation|" + JsonSerializer.Serialize(fact with { FilePath = Normalize(fact.FilePath, root) })
            )
        );
        rows.AddRange(
            (facts.DispatchFacts ?? []).Select(fact =>
                "dispatch|" + JsonSerializer.Serialize(fact with { FilePath = Normalize(fact.FilePath, root) })
            )
        );
        rows.AddRange(
            (facts.AllocationFacts ?? []).Select(fact =>
                "allocation|" + JsonSerializer.Serialize(fact with { FilePath = Normalize(fact.FilePath, root) })
            )
        );
        if (facts.CompilationHealth is null)
        {
            rows.Add("health|null");
        }
        else
        {
            rows.Add($"health|unlocated={facts.CompilationHealth.UnlocatedErrorCount}");
            rows.AddRange(
                facts.CompilationHealth.Files.Select(fact =>
                    "health-file|" + JsonSerializer.Serialize(fact with { FilePath = Normalize(fact.FilePath, root) })
                )
            );
            rows.AddRange(facts.CompilationHealth.PartialProjects.Select(fact => "health-project|" + JsonSerializer.Serialize(fact)));
        }
        return rows.Order(StringComparer.Ordinal).ToArray();
    }

    private static string FactHash(IEnumerable<string> facts) =>
        Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(string.Join('\n', facts) + "\n")));

    private static string Normalize(string path, string root) => Path.GetRelativePath(root, path).Replace('\\', '/');

    private static int CountOccurrences(string text, string value)
    {
        var count = 0;
        var start = 0;
        while ((start = text.IndexOf(value, start, StringComparison.Ordinal)) >= 0)
        {
            count++;
            start += value.Length;
        }
        return count;
    }

    private static IEnumerable<string> Lines(string text) => text.Split('\n', StringSplitOptions.RemoveEmptyEntries);
}
